### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by oameye** [rokzitko/sneg#3]
How is it that there is a mismatch between the version on the `main` branch on GitHub --- currently at v2.0.0 --- and the one that can be downloaded from [the package website](http://nrgljubljana.ijs.si/sneg/) --- at v2.0.5 ---  provided by [this GitHub archive link](https://github.com/rokzitko/sneg/archive/refs/heads/master.zip)?

**Comment by rokzitko** [comment]
There is only one branch, main, and it is currently at v2.0.5, as far as I can see (according to the version number in sneg.m file in commit c11a377).

**Comment by oameye** [comment]
Ha yes, I see. The mismatch is rather in the April release I downloaded, which is indeed in 8 commits behind.
![image](https://user-images.githubusercontent.com/57623933/222978279-c632ed8d-1d3b-4879-80bb-5b4025787987.png)
